apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dotnet-argo-application
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: "https://github.com/juan0331camilo/ArgoCD.git"
    path: Dev
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dotnet-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true